plugin:
    name: 'OctoDoc'
    description: 'leaderinternet.documentation::lang.plugin.description'
    author: 'Leader Internet'
    icon: oc-icon-book
    homepage: ''
navigation:
    documentation:
        label: Manual
        url: leaderinternet/documentation/documentation
        icon: icon-book
